### ISSUE TITLE
clamav-1.4.3 ctest fails

### ISSUE THREAD

**Issue by jonlar466** [Cisco-Talos/clamav#1564]
ctest fails for clamav 1.4.3
OS: RHEL 9.6

rustc 1.85.0 (4d91de4e4 2025-02-17)
json-c-json-c-0.15 is installed prior from source
ctest version 3.26.5

Compiled with these settings:

cmake -S /usr/local/src/clamav/clamav-1.4.3 -B /usr/local/src/clamav/clamav-1.4.3/build  \
 -D CMAKE_INSTALL_PREFIX=/usr/local/clamav -D CMAKE_INSTALL_LIBDIR=lib \
 -D APP_CONFIG_DIRECTORY=/usr/local/clamav/etc\
 -D DATABASE_DIRECTORY=/usr/local/clamav/share/clamav \
 -D ENABLE_JSON_SHARED=OFF

cmake --build /usr/local/src/clamav/clamav-1.4.3/build

ctest
"
Test project /usr/local/src/clamav/clamav-1.4.3/build
      Start  1: libclamav
 1/11 Test  #1: libclamav ........................   Passed    7.33 sec
      Start  2: libclamav_valgrind
 2/11 Test  #2: libclamav_valgrind ...............   Passed   70.25 sec
      Start  3: libclamav_rust
 3/11 Test  #3: libclamav_rust ...................   Passed    0.10 sec
      Start  4: clamscan
 4/11 Test  #4: clamscan .........................   Passed    4.59 sec
      Start  5: clamscan_valgrind
 5/11 Test  #5: clamscan_valgrind ................   Passed  136.34 sec
      Start  6: clamd
 6/11 Test  #6: clamd ............................   Passed   22.95 sec
      Start  7: clamd_valgrind
 7/11 Test  #7: clamd_valgrind ...................***Failed   58.15 sec
      Start  8: freshclam
 8/11 Test  #8: freshclam ........................   Passed    0.84 sec
      Start  9: freshclam_valgrind
 9/11 Test  #9: freshclam_valgrind ...............***Failed   25.28 sec
      Start 10: sigtool
10/11 Test #10: sigtool ..........................   Passed    0.43 sec
      Start 11: sigtool_valgrind
11/11 Test #11: sigtool_valgrind .................***Failed   11.47 sec

73% tests passed, 3 tests failed out of 11

Total Test time (real) = 337.75 sec

The following tests FAILED:
          7 - clamd_valgrind (Failed)
          9 - freshclam_valgrind (Failed)
         11 - sigtool_valgrind (Failed)
Errors while running CTest
Output from these tests are in: /usr/local/src/clamav/clamav-1.4.3/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
"

[LastTest.log](https://github.com/user-attachments/files/22089385/LastTest.log)

[ctest-verbose.txt](https://github.com/user-attachments/files/22116714/ctest-verbose.txt)

**Comment by jonlar466** [comment]
I have done some more tests on the same server, with different versions (not sure if this matters at all)
Updated to:
rust 1.89
cmake/ctest 4.1.1
json-c: 0.18
Python 3.11.11, pytest-8.4.1, pluggy-1.6.0

Same result after recompile & ctest with clamav 1.4.3

Also tried clamav 1.5.0-rc, there i only get 2 errors
clamd_valgrind & freshclam_valgrind

[ctest-150-verbose.txt](https://github.com/user-attachments/files/22173511/ctest-150-verbose.txt)

**Comment by val-ms** [comment]
Thanks for reporting this. My teammate @jhumlick is trying to solve one of the clamd failures and I have a PR in here fixing the other clamd failure and a possible libclamav issue: https://github.com/Cisco-Talos/clamav/pull/1554

I'm glad to hear you're not seeing the sigtool issue with 1.5.0-rc. We have made a variety of changes and fixed in sigtool including some to pass some new tests as well. 

We have an internal ticket in the backlog to solve the freshclam valgrind issue.

**Comment by stephengtuggy** [comment]
Hi. Just wanted to note that I'm still seeing one test failure, the freshclam_valgrind one, with https://github.com/Cisco-Talos/clamav/commit/0c7468e384cfb80fb34d950e80184f8660e7ff7b on Debian 13 "Trixie".
